import Link from 'next/link';
import { getCheckIns, listPatients } from '@/db/store';
import { buildSession, isoDay } from '@/engine/session';
import { PROTOCOLS } from '@/data/guidelines';

// The demo store lives in memory, so these pages must never be prerendered
// at build time -- a static snapshot would show the seeded history forever.
export const dynamic = 'force-dynamic';

export default function Home() {
  const today = isoDay(new Date());
  const sessions = listPatients().map((patient) =>
    buildSession(patient, getCheckIns(patient.id), today),
  );

  return (
    <main className="mx-auto w-full max-w-5xl flex-1 px-5 py-12">
      <p className="font-mono text-xs uppercase tracking-[0.16em] text-accent">
        Return-to-life accommodation engine
      </p>
      <h1 className="mt-4 max-w-[16ch] text-[clamp(2.4rem,1.6rem+3.4vw,4rem)] leading-[1.04]">
        The restriction is clear. The environment never hears it.
      </h1>
      <p className="mt-5 max-w-[52ch] text-lg text-ink-soft">
        Concussion tools talk to the patient. NaviTBI translates one person’s daily tolerance into
        instructions for the school, the manager and the family who keep overloading them.
      </p>

      <h2 className="mt-14 border-t border-rule pt-5 text-xl">Demonstration patients</h2>
      <p className="mt-2 max-w-[56ch] text-sm text-ink-soft">
        Histories are generated by the same synthetic model the evaluation harness measures, so
        these behave like the cohort in the results rather than like curated happy paths.
      </p>

      <ul className="mt-6 grid gap-px border border-rule bg-rule sm:grid-cols-3">
        {sessions.map((session) => (
          <li key={session.patient.id} className="bg-ground">
            <Link
              href={`/${session.patient.id}/today`}
              className="flex h-full flex-col gap-3 p-5 hover:bg-surface focus-visible:bg-surface"
            >
              <span className="text-2xl">{session.patient.displayName}</span>
              <span className="font-mono text-xs uppercase tracking-[0.1em] text-ink-faint">
                Day {session.daysSinceInjury} · {session.checkIns.length} check-ins
              </span>
              <span className="text-sm text-ink-soft">
                {PROTOCOLS[session.patient.protocol].name}, step {session.stage.step}
              </span>
              <span className="mt-auto pt-2 font-mono text-xs text-accent">
                Open →
              </span>
            </Link>
          </li>
        ))}
      </ul>

      <p className="mt-12 max-w-[62ch] border-l-2 border-caution bg-caution-surface p-4 text-sm">
        <strong className="font-semibold">Not medical advice.</strong> NaviTBI organises
        guideline-based information. It does not diagnose, does not issue clearance, and does not
        replace a clinician.
      </p>
    </main>
  );
}
